# Required metadata
sonar.projectKey=murv
sonar.projectName=murv
sonar.projectVersion=1.1

# Comma-separated paths to directories with sources (required)
sonar.sources=packages

sonar.verbose=true

# Tests

# sonar.javascript.lcov.reportPaths = coverage/lcov.info
# sonar.typescript.lcov.reportPaths = coverage/lcov.info
# sonar.testExecutionReportPaths = test-report.xml
# sonar.exclusions = **/*.test.*, **/*.spec.*

# Encoding of sources files
sonar.sourceEncoding = UTF-8
