import { IThemeCore, IThemeSystem } from "../../types";

export const getFlipkartDarkTheme = ({ ThemeCore }: { ThemeCore: IThemeCore }): IThemeSystem => ({
  color: {
    surface: {
      neutral: {
        default: ThemeCore.color.grey[900],
        hover: ThemeCore.color.grey[800],
        pressed: ThemeCore.color.grey[700],
      },
      brand: {
        default: ThemeCore.color.blue[400],
        hover: ThemeCore.color.blue[300],
        pressed: ThemeCore.color.blue[200],
      },
      accent: {
        default: ThemeCore.color.yellow[900],
        hover: ThemeCore.color.yellow[800],
        pressed: ThemeCore.color.yellow[700],
      },
      information: {
        default: ThemeCore.color.grey[800],
        hover: ThemeCore.color.grey[700],
        pressed: ThemeCore.color.grey[600],
      },
      inverse: {
        default: ThemeCore.color.grey[300],
        hover: ThemeCore.color.grey[200],
        pressed: ThemeCore.color.grey[100],
      },
      success: {
        default: ThemeCore.color.green[800],
        hover: ThemeCore.color.green[700],
        pressed: ThemeCore.color.green[600],
      },
      warning: {
        default: ThemeCore.color.mustard[800],
        hover: ThemeCore.color.mustard[700],
        pressed: ThemeCore.color.mustard[600],
      },
      danger: {
        default: ThemeCore.color.red[1000],
        hover: ThemeCore.color.red[900],
        pressed: ThemeCore.color.red[800],
      },
      selected: {
        default: ThemeCore.color.blue[800],
        hover: ThemeCore.color.blue[700],
        pressed: ThemeCore.color.blue[600],
      },
      disabled: {
        default: ThemeCore.color.grey[800],
        hover: ThemeCore.color.grey[800],
        pressed: ThemeCore.color.grey[800],
      },
      input: {
        default: ThemeCore.color.grey[1000],
        hover: ThemeCore.color.grey[900],
        pressed: ThemeCore.color.grey[850],
      },
    },
    tag: {
      promotion: ThemeCore.color.magenta[800],
      saving: ThemeCore.color.yellow[800],
      combo: ThemeCore.color.teal[800],
      category: ThemeCore.color.grey[800],
      recommended: ThemeCore.color.grey[400],
    },
    text: {
      primary: ThemeCore.color.grey[50],
      secondary: ThemeCore.color.grey[100],
      brand: ThemeCore.color.blue[200],
      information: ThemeCore.color.blue[200],
      inverse: ThemeCore.color.grey[1000],
      success: ThemeCore.color.green[200],
      warning: ThemeCore.color.mustard[200],
      danger: ThemeCore.color.red[200],
      selected: ThemeCore.color.blue[900],
      disabled: ThemeCore.color.grey[500],
    },
    skeleton: {
      neutral: ThemeCore.color.grey[800],
      subtle: ThemeCore.color.grey[900],
    },
    icon: {
      primary: ThemeCore.color.grey[50],
      secondary: ThemeCore.color.grey[100],
      brand: ThemeCore.color.blue[200],
      information: ThemeCore.color.blue[200],
      inverse: ThemeCore.color.grey[1000],
      success: ThemeCore.color.green[200],
      warning: ThemeCore.color.mustard[200],
      danger: ThemeCore.color.red[200],
      selected: ThemeCore.color.blue[900],
      disabled: ThemeCore.color.grey[500],
    },
    stroke: {
      primary: ThemeCore.color.grey[800],
      secondary: ThemeCore.color.grey[800],
      brand: ThemeCore.color.blue[200],
      brandlight: ThemeCore.color.blue[400],
      accent: ThemeCore.color.yellow[300],
      information: ThemeCore.color.blue[300],
      inverse: ThemeCore.color.grey[1000],
      success: ThemeCore.color.green[700],
      warning: ThemeCore.color.mustard[700],
      danger: ThemeCore.color.red[200],
      dangerlight: ThemeCore.color.red[900],
      selected: ThemeCore.color.blue[700],
      disabled: ThemeCore.color.grey[700],
    },
  },
  spacing: {
    0: ThemeCore.spacing[0],
    xxxs: ThemeCore.spacing[1],
    xxs: ThemeCore.spacing[2],
    xs: ThemeCore.spacing[3],
    s: ThemeCore.spacing[4],
    m: ThemeCore.spacing[5],
    l: ThemeCore.spacing[6],
    xl: ThemeCore.spacing[7],
    xxl: ThemeCore.spacing[9],
    xxxl: ThemeCore.spacing[11],
  },
  radius: {
    0: ThemeCore.radius[0],
    xxs: ThemeCore.radius.xxs,
    xs: ThemeCore.radius.xs,
    s: ThemeCore.radius.s,
    m: ThemeCore.radius.m,
    l: ThemeCore.radius.l,
    xl: ThemeCore.radius.xl,
    xxl: ThemeCore.radius.xxl,
    xxxl: ThemeCore.radius.xxxl,
  },
  stroke: {
    0: ThemeCore.stroke.solid[0],
    standard: ThemeCore.stroke.solid[2],
    thin: ThemeCore.stroke.solid[1],
    thick: ThemeCore.stroke.solid[3],
  },
  shadow: {
    overflow: ThemeCore.shadow[10],
    overlay: ThemeCore.shadow[20],
    floating: ThemeCore.shadow[30],
  },
  zIndex: {
    level0: ThemeCore.zIndex.level0,
    level1: ThemeCore.zIndex.level1,
    level2: ThemeCore.zIndex.level2,
    level3: ThemeCore.zIndex.level3,
    level99: ThemeCore.zIndex.level99,
  },
  aspectRatio: {
    square: ThemeCore.aspectRatio.square,
    landscape: ThemeCore.aspectRatio.landscape,
    portrait: ThemeCore.aspectRatio.portrait,
    wide: ThemeCore.aspectRatio.wide,
  },
  opacity: {
    disabled: ThemeCore.opacity[300],
    loading: ThemeCore.opacity[200],
    blanket: ThemeCore.opacity[400],
  },
  typography: {
    heading: {
      s: {
        weight: ThemeCore.typography.weight.medium,
        size: ThemeCore.typography.size.l,
        letterSpacing: ThemeCore.typography.letterSpacing.l,
        lineHeight: ThemeCore.typography.lineHeight.m,
      },
      m: {
        weight: ThemeCore.typography.weight.medium,
        size: ThemeCore.typography.size.xl,
        letterSpacing: ThemeCore.typography.letterSpacing.l,
        lineHeight: ThemeCore.typography.lineHeight.m,
      },
      l: {
        weight: ThemeCore.typography.weight.medium,
        size: ThemeCore.typography.size.xxl,
        letterSpacing: ThemeCore.typography.letterSpacing.l,
        lineHeight: ThemeCore.typography.lineHeight.l,
      },
    },
    body: {
      s: {
        weight: ThemeCore.typography.weight.medium,
        size: ThemeCore.typography.size.m,
        letterSpacing: ThemeCore.typography.letterSpacing.m,
        lineHeight: ThemeCore.typography.lineHeight.s,
      },
      sBold: {
        weight: ThemeCore.typography.weight.bold,
        size: ThemeCore.typography.size.m,
        letterSpacing: ThemeCore.typography.letterSpacing.m,
        lineHeight: ThemeCore.typography.lineHeight.s,
      },
    },
    subtext: {
      s: {
        weight: ThemeCore.typography.weight.regular,
        size: ThemeCore.typography.size.s,
        letterSpacing: ThemeCore.typography.letterSpacing.s,
        lineHeight: ThemeCore.typography.lineHeight.xs,
      },
    },
  },
});
